/**
 * @file Contains type definitions for all the different sections that can be added to a landing page.
 */

import type { NavMenuItem, SocialLink, FeatureItem, TestimonialItem, PricingPlan, FAQItem, WhyChooseUsItem, GalleryItem, CourseChapter, HeroSlide, HeroButton } from './shared';
import type { ProductItem } from './product';
import type { CrmFormField } from './crm';


/** Defines the animation style for a section when it scrolls into view. */
export type SectionAnimation = 'none' | 'fade-in-up';

/**
 * Data structure for the Navigation section.
 * @interface
 */
export interface NavSectionData {
  logoType: 'text' | 'image';
  logoText: string;
  logoImagePrompt?: string;
  logoWidth: number;
  navStyle: 'sticky' | 'static';
  layout: 'standard' | 'centered' | 'split';
  mobileLayout: 'hamburger' | 'bottom';
  menuItems: NavMenuItem[];
  signInButtonEnabled: boolean;
  signInButtonText: string;
  cartButtonEnabled: boolean;
  navTransparency: 'none' | 'on-hero';
}

/**
 * Data structure for the Hero section.
 * @interface
 */
export interface HeroSectionData {
  layout: 'background' | 'split' | 'form_overlay' | 'split_embed' | 'split_video' | 'embed_overlay';
  title: string;
  subtitle: string;
  buttons?: HeroButton[];
  buttonLayout?: 'horizontal' | 'vertical';
  backgroundType: 'image' | 'video' | 'slider';
  imagePrompt?: string;
  slides?: HeroSlide[];
  videoSource?: 'youtube' | 'vimeo';
  youtubeVideoId?: string;
  vimeoVideoId?: string;
  backgroundVideoEmbedCode?: string;
  splitImagePrompt?: string;
  splitEmbedCode?: string;
  splitEmbedWidth?: string;
  splitEmbedHeight?: string;
  splitVideoSource?: 'youtube' | 'vimeo';
  splitYoutubeVideoId?: string;
  splitVimeoVideoId?: string;
  splitVideoEmbedCode?: string;
  backgroundColorLight?: string; // e.g. slate-100
  backgroundColorDark?: string; // e.g. slate-800
  formId?: string;
  formTitle?: string;
  fields?: CrmFormField[];
  animateText?: boolean;
  animation?: SectionAnimation;

  // Deprecated single CTA fields for backward compatibility
  ctaText?: string;
  ctaLink?: string;
  buttonColor?: string;
}

/**
 * Data structure for the Features section.
 * @interface
 */
export interface FeaturesSectionData {
  title: string;
  subtitle: string;
  items: FeatureItem[];
  animation?: SectionAnimation;
}

/**
 * Data structure for the Video section.
 * @interface
 */
export interface VideoSectionData {
  title: string;
  subtitle: string;
  videoSource: 'youtube' | 'vimeo';
  youtubeVideoId?: string;
  vimeoVideoId?: string;
  videoEmbedCode?: string;
  animation?: SectionAnimation;
}

/**
 * Data structure for the Testimonials section.
 * @interface
 */
export interface TestimonialsSectionData {
  title: string;
  subtitle: string;
  items: TestimonialItem[];
  animation?: SectionAnimation;
}

/**
 * Data structure for the Pricing section.
 * @interface
 */
export interface PricingSectionData {
  title: string;
  subtitle: string;
  plans: PricingPlan[];
  animation?: SectionAnimation;
}

/**
 * Data structure for the FAQ section.
 * @interface
 */
export interface FAQSectionData {
  title: string;
  subtitle: string;
  items: FAQItem[];
  animation?: SectionAnimation;
}

/**
 * Data structure for the Call To Action (CTA) section.
 * @interface
 */
export interface CTASectionData {
  title: string;
  subtitle: string;
  ctaText: string;
  ctaLink: string;
  animation?: SectionAnimation;
}

/**
 * Data structure for the Contact section.
 * @interface
 */
export interface ContactSectionData {
  title: string;
  subtitle: string;
  animation?: SectionAnimation;
}

/**
 * Data structure for the Booking section.
 * @interface
 */
export interface BookingSectionData {
  title: string;
  subtitle: string;
  ctaText: string;
  bookingEmbedCode: string;
  animation?: SectionAnimation;
}

/**
 * Data structure for the 'Why Choose Us' section.
 * @interface
 */
export interface WhyChooseUsSectionData {
    title: string;
    subtitle: string;
    items: WhyChooseUsItem[];
    animation?: SectionAnimation;
}

/**
 * Data structure for the Gallery section.
 * @interface
 */
export interface GallerySectionData {
    title: string;
    subtitle: string;
    items: GalleryItem[];
    animation?: SectionAnimation;
}

/**
 * Data structure for the Products section as generated by the AI.
 * @interface
 */
export interface GeneratedProductsSectionData {
    title: string;
    subtitle: string;
    items: ProductItem[];
    animation?: SectionAnimation;
}

/**
 * Data structure for the Products section as stored in the page's data.
 * @interface
 */
export interface ProductsSectionData {
    title: string;
    subtitle: string;
    itemIds: string[]; // Stores UUIDs of products from the `products` table
    animation?: SectionAnimation;
}

/**
 * Data structure for the Footer section.
 * @interface
 */
export interface FooterSectionData {
    copyrightText: string;
    socialLinks: SocialLink[];
}

/**
 * Data structure for the Course section.
 * @interface
 */
export interface CourseSectionData {
    title: string;
    subtitle: string;
    description: string;
    mediaType: 'image' | 'video';
    imagePrompt?: string;
    videoSource: 'youtube';
    youtubeVideoId?: string;
    chapters: CourseChapter[];
    price: number;
    currency: string;
    buyButtonText: string;
    certificateEnabled: boolean;
    certificateTitle: string;
    courseProviderName: string;
    backgroundColor?: string;
    darkBackgroundColor?: string;
    enforceSequence: boolean;
    animation?: SectionAnimation;
}

/**
 * Data structure for a section that displays a custom form.
 * @interface
 */
export interface CustomFormSectionData {
    title: string;
    subtitle: string;
    formId: string;
    fields?: CrmFormField[]; // For published data
    animation?: SectionAnimation;
}

/**
 * Data structure for a section that embeds external content.
 * @interface
 */
export interface EmbedSectionData {
  title: string;
  subtitle: string;
  embedType: 'floating-script' | 'inline-iframe';
  embedCode: string;
  apiKey: string;
  animation?: SectionAnimation;
}